### ISSUE TITLE
getRealIpV6函数里json.load出现错误

### ISSUE THREAD

**Issue by MonsoonTime** [quancs/AliDDNS#3]
Traceback (most recent call last):
  File "/usr/local/ddns/aliddns.py", line 93, in <module>
    ip=getRealIpV6()
  File "/usr/local/ddns/aliddns.py", line 27, in getRealIpV6
    jsonData = json.loads(html)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 346, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 1 column 5 - line 1 column 40 (char 4 - 39)

我一步步执行着看了下，html可以得到一个IPV6地址，html='2409:8a70:f927:xxxx:xxxx:c2ff:fe80:a63d'。这个不是作者期待的格式吧？请问是哪一步出了问题？谢谢

**Comment by quancs** [comment]
修复了，你看下呢。原来的问题是ipv6网址返回的格式存在问题，期待json格式，返回的直接就是v6地址
